config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resource :session, only: [:new, :create, :destroy]
  resource :setting, only: [:show, :update]

  resources :artists, only: [:index, :show]
  resources :stream, only: [:new]
  resources :transcoded_stream, only: [:new]
  resources :songs, only: [:index, :show]
  resources :albums, only: [:index, :show]

  resources :users, except: [:show] do
    resource :settings, only: [:update]
  end

  resources :playlists, except: [:show, :new, :edit] do
    resource :songs, only: [:show, :create, :destroy], module: 'playlists'
  end

  namespace :current_playlist do
    resource :songs, only: [:show, :update, :create, :destroy]
  end

  namespace :favorite_playlist do
    resource :songs, only: [:show, :create, :destroy]
  end

  namespace :dialog do
    resources :playlists, only: [:index]
  end

  get '/403', to: 'errors#forbidden', as: :forbidden
  get '/404', to: 'errors#not_found', as: :not_found
  get '/422', to: 'errors#unprocessable_entity', as: :unprocessable_entity
  get '/500', to: 'errors#internal_server_error', as: :internal_server_error
end

app/views/shared/_dialog.html.erb
<section id='js-dialog' class='dialog hidden' data-controller='dialog'>
  <header class='dialog__header display__space-between'>
    <h2 class='dialog__title'><%= t('text.add_to_playlist') %></h2>
    <span class='pointer-cursor' data-action='click->dialog#hide'>
      <%= icon_tag 'close', title: t('label.close') %>
    </span>
  </header>
  <div class='dialog__content position-relative'>
    <div id='js-dialog-content'>
    </div>
    <div id='js-dialog-loader' class='overlay hidden' data-controller='loader'>
      <%= loader_tag size: 'small' %>
    </div>
  </div>
</section>

app/views/shared/_empty_alert.html.erb
<div class='overlay'>
  <div class='notice'>
    <% if has_icon %>
      <div class='notice__text'>
        <%= icon_tag 'music-off', large: 'large' %>
      </div>
    <% end %>
    <div class='notice__text'><%= t('text.no_items') %></div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class='flash__body <%= "flash__body--#{key}" %>' data-controller='flash' data-flash-timeout='2500'>
    <%= h value %>
  </div>
<% end %>

app/views/shared/_flash.js.erb
App.renderContent('#js-flash', '<%= j(render 'shared/flash.html.erb') %>')

app/views/shared/_mini_player.html.erb
<div id='js-mini-player' class='player player--mini' data-controller='mini-player' data-turbolinks-permanent>
  <div data-action='click->mini-player#expand' class='player__info display__align-center text-truncate'>
    <span><%= icon_tag 'expand-less', size: 'large', title: t('text.expand_player') %></span>
    <span data-target='mini-player.songName' class='text-truncate'></span>
    <span data-target='mini-player.loader' class='hidden'><%= loader_tag(size: 'small') %></span>
  </div>
  <div class='player__control display__space-between'>
    <span data-action='click->mini-player#play' class='player__control__main pointer-cursor' data-target='mini-player.playButton'><%= icon_tag 'play', size: 'large', title: t('text.play_song') %></span>
    <span data-action='click->mini-player#pause' class='player__control__main pointer-cursor hidden' data-target='mini-player.pauseButton'><%= icon_tag 'pause', size: 'large', title: t('text.pause_song') %></span>
    <span data-action='click->mini-player#next' class='pointer-cursor'><%= icon_tag 'fast-forward', size: 'large', title: t('text.next_song') %></span>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav class='layout__nav-bar'>
  <ul class='tab'>
    <li class='tab__item <%= 'tab__item--active' if is_active?(controller: 'albums') %>'>
      <%= link_to t('label.albums'), albums_path %>
    </li>
    <li class='tab__item <%= 'tab__item--active' if is_active?(controller: 'artists') %>'>
      <%= link_to t('label.artists'), artists_path %>
    </li>
    <li class='tab__item <%= 'tab__item--active' if is_active?(controller: 'songs') %>'>
      <%= link_to t('label.songs'), songs_path %>
    </li>
    <li class='tab__item <%= 'tab__item--active' if is_active?(controller: 'settings') %>'>
      <%= link_to t('label.settings'), setting_path %>
    </li>
  </ul>
</nav>

app/views/shared/_player.html.erb
<div class='player' data-controller='player'>
  <div data-target='player.header' class='player__header position-relative'>
    <div data-target='player.headerContent' class='player__header__content'>
      <div class='heading'>
        <div class='heading__image'>
          <img data-target='player.image' class='image image--small' />
        </div>
        <div class='heading__body'>
          <div class='heading__body__text heading__body__text--main text-truncate' data-target='player.songName'></div>
          <div class='heading__body__text text-truncate' data-target='player.albumName'></div>
          <div class='heading__body__text text-truncate' data-target='player.artistName'></div>
          <div class='player__timer monospace-font'>
            <span class='player__timer__item player__timer__item--main' data-target='player.songTimer'></span>
            <span class='player__timer__item'>/</span>
            <span class='player__timer__item' data-target='player.songDuration'></span>
          </div>
        </div>
      </div>
      <div class='player__progress pointer-cursor'>
        <progress data-target='player.progress' data-action='click->player#seek' class='display__full-width display__flex' max='100'></progress>
      </div>
    </div>
    <div data-target='player.loader' class='overlay hidden'>
      <%= loader_tag %>
    </div>
  </div>
  <div class='player__control display__space-between'>
    <div class='player__control__minor pointer-cursor' data-action='click->player#nextMode'>
      <span data-target='player.modeButton'><%= icon_tag 'repeat', title: t('text.repeat_mode') %></span>
      <span data-target='player.modeButton'><%= icon_tag 'repeat-one', title: t('text.single_mode') %></span>
      <span data-target='player.modeButton'><%= icon_tag 'shuffle', title: t('text.shuffle_mode') %></span>
    </div>
    <div>
      <span class='pointer-cursor' data-action='click->player#previous'><%= icon_tag 'rewind', size: 'large', title: t('text.previous_song') %></span>
      <span data-action='click->player#play' class='player__control__main pointer-cursor' data-target='player.playButton'><%= icon_tag 'play', size: 'large', title: t('text.play_song') %></span>
      <span data-action='click->player#pause' class='player__control__main pointer-cursor hidden' data-target='player.pauseButton'><%= icon_tag 'pause', size: 'large', title: t('text.pause_song') %></span>
      <span data-action='click->player#next' class='pointer-cursor'><%= icon_tag 'fast-forward', size: 'large', title: t('text.next_song') %></span>
    </div>
    <div data-target='player.favoriteButton' data-action='click->player#toggleFavorite' class='player__control__minor pointer-cursor'>
      <%= icon_tag 'heart', title: t('text.toggle_favorite') %>
    </div>
  </div>
  <div class='player__footer display__text-center hidden' data-action='click->player#collapse'>
    <%= icon_tag 'expand-more', size: 'large', title: t('text.collapse_player') %>
  </div>
</div>

app/views/shared/_playlist.html.erb
<div id='js-playlist' class='playlist display__full-height' data-controller='ajax' data-ajax-loader='#js-playlist-loader'>
  <div id='js-playlist-nav' class='playlist__nav'>
    <%= render 'playlists/nav' %>
  </div>
  <div class='display__full-height noscroll position-relative'>
    <div class='playlist__container'>
      <div class='playlist__content' id='js-playlist-content'></div>
    </div>
    <div id='js-playlist-loader' class='overlay hidden' data-controller='loader'>
      <%= loader_tag %>
    </div>
  </div>
</div>

app/views/shared/_playlist.js.erb
App.renderPlaylistContent('<%= j(html) %>');
App.renderContent('#js-playlist-nav', '<%= j(render 'playlists/nav') %>');

app/views/shared/_search_bar.html.erb
<div class='layout__search-bar display__space-between'>
  <div class='avatar'>
    <!-- Placeholder for search-bar layout to keep search bar input center -->
  </div>
  <div class='input' data-controller='search' data-search-resource='<%= params[:controller] %>'>
    <div class='input__icon'>
      <%= icon_tag 'search', size: 'large' %>
    </div>
    <input id='js-search-input' data-target='search.input' data-action='keydown->search#query' value='<%= params[:query] %>' />
    <div class='input__icon input__icon--right hidden' data-target='search.loader'>
      <%= loader_tag size: 'small' %>
    </div>
  </div>
  <div data-controller='dropdown' class='dropdown'>
    <span data-action='click->dropdown#show'><%= avatar_tag Current.user %></span>
    <div data-target='dropdown.list' class='hidden dropdown__list'>
      <%= link_to t('label.manage_users'), users_path, class: 'dropdown__item' if is_admin? %>
      <%= link_to t('label.update_profile'), edit_user_path(Current.user), class: 'dropdown__item' %>
      <%= link_to t('label.logout'), session_path, method: :delete, class: 'dropdown__item' %>
    </div>
  </div>
</div>