config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resource :session, only: [:new, :create, :destroy]
  resource :setting, only: [:show, :update]

  resources :artists, only: [:index, :show]
  resources :stream, only: [:new]
  resources :transcoded_stream, only: [:new]
  resources :songs, only: [:index, :show]
  resources :albums, only: [:index, :show]

  resources :users, except: [:show] do
    resource :settings, only: [:update]
  end

  resources :playlists, except: [:show, :new, :edit] do
    resource :songs, only: [:show, :create, :destroy], module: 'playlists'
  end

  namespace :current_playlist do
    resource :songs, only: [:show, :update, :create, :destroy]
  end

  namespace :favorite_playlist do
    resource :songs, only: [:show, :create, :destroy]
  end

  namespace :dialog do
    resources :playlists, only: [:index]
  end

  get '/403', to: 'errors#forbidden', as: :forbidden
  get '/404', to: 'errors#not_found', as: :not_found
  get '/422', to: 'errors#unprocessable_entity', as: :unprocessable_entity
  get '/500', to: 'errors#internal_server_error', as: :internal_server_error
end

app/models/playlist.rb
# frozen_string_literal: true

class Playlist < ApplicationRecord
  validates :name, presence: true, if: :require_name?

  has_and_belongs_to_many :songs, -> { order('playlists_songs.created_at') }
  belongs_to :user

  def buildin?
    false
  end

  def current?
    type == 'CurrentPlaylist'
  end

  def favorite?
    type == 'FavoritePlaylist'
  end

  private

    def require_name?
      true
    end
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  include Searchable

  validates :name, :file_path, :md5_hash, presence: true

  belongs_to :album, touch: true
  belongs_to :artist, touch: true
  has_and_belongs_to_many :playlists

  search_by :name, associations: [:artist, :album]

  def format
    file_format = MediaFile.format(file_path)
    file_format.in?(Stream::TRANSCODING_FORMATS) ? Stream::TRANSCODE_FORMAT : file_format
  end
end

app/controllers/current_playlist/songs_controller.rb
# frozen_string_literal: true

class CurrentPlaylist::SongsController < Playlists::SongsController
  def update
    song_ids = songs_params[:song_ids]
    raise MusicError::Forbidden if song_ids.empty?

    @playlist.songs.clear
    @playlist.song_ids = song_ids; show
  end

  private

    def find_playlist
      @playlist = Current.user.current_playlist
    end
end

app/controllers/dialog/playlists_controller.rb
# frozen_string_literal: true

class Dialog::PlaylistsController < PlaylistsController
end

app/controllers/favorite_playlist/songs_controller.rb
# frozen_string_literal: true

class FavoritePlaylist::SongsController < Playlists::SongsController
  private

    def find_playlist
      @playlist = Current.user.favorite_playlist
    end
end

app/controllers/playlists/songs_controller.rb
# frozen_string_literal: true

class Playlists::SongsController < ApplicationController
  include Pagy::Backend

  before_action :require_login
  before_action :find_playlist
  before_action :find_songs, only: [:create, :destroy]

  def show
    @pagy, @songs = pagy_countless(@playlist.songs.includes(:artist))
  end

  def create
    @playlist.songs.push(@songs)
    flash.now[:success] = t('success.add_to_playlist')

    # for refresh playlist content, when first song add to playlist
    show if @playlist.songs.size == 1
  rescue ActiveRecord::RecordNotUnique
    flash.now[:error] = t('error.already_in_playlist')
  end

  def destroy
    if songs_params[:clear_all]
      @playlist.songs.clear
    else
      @playlist.songs.destroy(@songs)
      flash.now[:success] = t('success.delete_from_playlist')
    end

    # for refresh playlist content, when remove last song from playlist
    show if @playlist.songs.empty?
  end

  private

    def find_playlist
      @playlist = Current.user.all_playlists.find(songs_params[:playlist_id])
    end

    def find_songs
      @songs = Song.find(songs_params[:song_ids]) unless songs_params[:clear_all]
    end

    def songs_params
      params.permit(:playlist_id, :clear_all, song_ids: [])
    end
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

class PlaylistsController < ApplicationController
  include Pagy::Backend

  before_action :require_login
  before_action :find_playlist, only: [:destroy, :update]

  def index
    @pagy, @playlists = pagy_countless(Current.user.playlists.order(created_at: :desc))
  end

  def create
    @playlist = Current.user.playlists.new playlist_params

    if @playlist.save
      flash.now[:success] = t('success.create')
    else
      flash.now[:error] = @playlist.errors.full_messages.join(' ')
    end
  end

  def update
    @playlist.update(playlist_params)
  end

  def destroy
    @playlist.destroy
    index; render 'index'
  end

  private

    def find_playlist
      @playlist = Current.user.playlists.find(params[:id])
    end

    def playlist_params
      params.require(:playlist).permit(:name)
    end
end

app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  include Pagy::Backend

  before_action :require_login

  def index
    records = Song.search(params[:query]).includes(:artist, :album).order(:name)
    @pagy, @songs = pagy_countless(records)
  end

  def show
    @song = Song.find(params[:id])
  end
end

app/views/playlists/songs/_list.html.erb
<div data-controller='infinite-scroll' data-infinite-scroll-container='.playlist__container' data-infinite-scroll-next-url='<%= next_url %>'>
  <ul class='list' id='js-playlist-list-content' data-action='click->playlist-songs#actionHandler'>
    <%= render partial: 'song', collection: @songs, cached: true %>
  </ul>
  <div data-target='infinite-scroll.trigger' class='display__justify-align-center'>
    <% if @pagy.next %>
      <%= loader_tag expand: true %>
    <% end %>
  </div>
</div>

app/views/playlists/songs/_show.html.erb
<div data-controller='playlist-songs' data-playlist-songs-playlist-id='<%= @playlist.id %>' class='display__full-height display__flex-vertical'>
  <div class='heading' data-controller='playlist' data-playlist-id='<%= @playlist.id %>'>
    <div class='heading__header'>
      <%= link_to playlists_path, remote: true, data: { show_loader: true } do %>
        <%= icon_tag 'chevron-left', title: t('text.go_back') %>
      <% end %>
    </div>
    <div class='heading__body'>
      <div class='heading__body__text'>
        <span data-target='playlist.name'><%= @playlist.name %></span>
        <div class='input'>
          <input data-target='playlist.nameInput' data-action='blur->playlist#updateName keydown->playlist#updateNameOnEnter' class='hidden' />
        </div>
      </div>
      <div class='heading__body__text'>
        <span data-target='playlist-songs.count'><%= @playlist.songs.size %></span>
        <span> <%= t('label.tracks') %><span>
      </div>
    </div>
    <div class='heading__footer'>
      <div data-controller='dropdown' class='dropdown'>
        <span data-action='click->dropdown#show'><%= icon_tag 'more-vertical', title: t('label.more') %></span>
        <div data-target='dropdown.list' class='hidden dropdown__list'>
          <% unless @songs.blank? %>
            <%= link_to t('label.play_all'), current_playlist_songs_path(song_ids: @playlist.song_ids), method: :put, remote: true, data: { target: 'playlist-songs.playAllLink' }, class: 'dropdown__item' %>
            <a class='dropdown__item' data-action='playlist-songs#clear'><%= t('label.clear') %></a>
          <% end %>
          <%= link_to t('label.delete'), playlist_path(@playlist), method: :delete, remote: true, class: 'dropdown__item', data: { show_loader: true } %>
          <a data-action='playlist#rename' class='dropdown__item'><%= t('label.rename') %></a>
        </div>
      </div>
    </div>
  </div>
  <% if @playlist.present? %>
    <%= render partial: 'list', locals: { next_url: local_assigns[:next_url] || pagy_next_url(@pagy) } %>
  <% end %>
</div>

app/views/playlists/songs/_show_buildin.html.erb
<div data-controller='playlist-songs' data-playlist-songs-playlist-id='<%= @playlist.id %>' data-playlist-songs-is-current='<%= @playlist.current? %>' class='display__full-height'>
  <% if @songs.empty? %>
    <%= empty_alert_tag %>
  <% else %>
    <div class='heading'>
      <div class='heading__body'>
        <div class='heading__body__text'>
          <span data-target='playlist-songs.count'><%= @playlist.songs.size %></span>
          <span> <%= t('label.tracks') %></span>
        </div>
      </div>
      <div class='heading__footer'>
        <div data-controller='dropdown' class='dropdown'>
          <span data-action='click->dropdown#show'><%= icon_tag 'more-vertical', title: t('label.more') %></span>
          <div data-target='dropdown.list' class='hidden dropdown__list'>
            <% unless @playlist.current? %>
              <%= link_to t('label.play_all'), current_playlist_songs_path(song_ids: @playlist.song_ids), method: :put, remote: true, data: { target: 'playlist-songs.playAllLink' }, class: 'dropdown__item' %>
            <% end %>
            <a class='dropdown__item' data-action='playlist-songs#clear'><%= t('label.clear') %></a>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: 'list', locals: { next_url: local_assigns[:next_url] || next_url_for_path(playlist_path(@playlist), @pagy) } %>
  <% end %>
</div>

app/views/playlists/songs/_song.html.erb
<li class='list__item pointer-cursor' data-target='playlist-songs.item' data-song-id='<%= song.id %>' data-playlist-songs-action='play'>
  <span class='list__item__content'>
    <span class='list__item__info list__item__info--main'><%= song.name %></span>
    <span class='list__item__info'><%= song.artist.title %></span>
  </span>
  <span class='list__item__content list__item__content--minor'>
    <span class='list__item__info list__item__info--action'>
      <span data-playlist-songs-action='showPlaylistsDialog'><%= icon_tag 'playlist-add', size: 'small', title: t('text.add_to_playlist') %></span>
      <span data-playlist-songs-action='delete'><%= icon_tag 'delete', size: 'small', title: t('label.delete') %></span>
    </span>
    <span class='list__item__info list__item__info--minor monospace-font'><%= format_duration(song.length) %></span>
  </span>
</li>

app/views/playlists/songs/create.js.erb
(function() {
  var playlistElement = App.playlistElement('<%= @playlist.id %>')

  <% if @playlist.songs.size > 1 %>
    var infiniteScrollElement = document.querySelector("#js-playlist-content [data-controller='infinite-scroll']");
    var hasNoNextUrl = infiniteScrollElement && !infiniteScrollElement.dataset.infiniteScrollNextUrl

    if (playlistElement && hasNoNextUrl) {
      App.dispatchEvent(playlistElement, 'playlistSongs:updateCount', '<%= @playlist.songs.size %>');
      App.dispatchEvent(playlistElement, 'playlistSongs:updatePlayAllLink', '<%= current_playlist_songs_path(song_ids: @playlist.song_ids) %>');
      document.querySelector('#js-playlist-list-content').insertAdjacentHTML('beforeend', "<%= j(render partial: 'song', collection: @songs, cached: true)%>");
    }
  <% else %>
    if (playlistElement) {
      App.renderPlaylistContent("<%= j @playlist.buildin? ? render('show_buildin') : render('show') %>")
    }
  <% end %>
})();

<%= render_flash %>

app/views/playlists/songs/destroy.js.erb
(function() {
  var playlistElement = App.playlistElement('<%= @playlist.id %>')

  <% if @playlist.songs.empty? %>
    if (playlistElement) {
      App.renderPlaylistContent("<%= j @playlist.buildin? ? render('show_buildin') : render('show') %>")
    }
  <% else %>
    if (playlistElement) {
      App.dispatchEvent(playlistElement, 'playlistSongs:updateCount', '<%= @playlist.songs.size %>');
      App.dispatchEvent(playlistElement, 'playlistSongs:updatePlayAllLink', '<%= current_playlist_songs_path(song_ids: @playlist.song_ids) %>');
    }
  <% end %>
})();

<%= render_flash %>

app/views/playlists/songs/show.js.erb
<% if @pagy.page == 1 %>
  <%= render_playlist(render 'show') %>
<% else %>
  App.appedNextPageContentTo('#js-playlist-list-content', '<%= j(render partial: 'song', collection: @songs, cached: true) %>', '<%= pagy_next_url(@pagy) %>')
<% end %>