config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resource :session, only: [:new, :create, :destroy]
  resource :setting, only: [:show, :update]

  resources :artists, only: [:index, :show]
  resources :stream, only: [:new]
  resources :transcoded_stream, only: [:new]
  resources :songs, only: [:index, :show]
  resources :albums, only: [:index, :show]

  resources :users, except: [:show] do
    resource :settings, only: [:update]
  end

  resources :playlists, except: [:show, :new, :edit] do
    resource :songs, only: [:show, :create, :destroy], module: 'playlists'
  end

  namespace :current_playlist do
    resource :songs, only: [:show, :update, :create, :destroy]
  end

  namespace :favorite_playlist do
    resource :songs, only: [:show, :create, :destroy]
  end

  namespace :dialog do
    resources :playlists, only: [:index]
  end

  get '/403', to: 'errors#forbidden', as: :forbidden
  get '/404', to: 'errors#not_found', as: :not_found
  get '/422', to: 'errors#unprocessable_entity', as: :unprocessable_entity
  get '/500', to: 'errors#internal_server_error', as: :internal_server_error
end

app/models/playlist.rb
# frozen_string_literal: true

class Playlist < ApplicationRecord
  validates :name, presence: true, if: :require_name?

  has_and_belongs_to_many :songs, -> { order('playlists_songs.created_at') }
  belongs_to :user

  def buildin?
    false
  end

  def current?
    type == 'CurrentPlaylist'
  end

  def favorite?
    type == 'FavoritePlaylist'
  end

  private

    def require_name?
      true
    end
end

app/controllers/dialog/playlists_controller.rb
# frozen_string_literal: true

class Dialog::PlaylistsController < PlaylistsController
end

app/controllers/playlists/songs_controller.rb
# frozen_string_literal: true

class Playlists::SongsController < ApplicationController
  include Pagy::Backend

  before_action :require_login
  before_action :find_playlist
  before_action :find_songs, only: [:create, :destroy]

  def show
    @pagy, @songs = pagy_countless(@playlist.songs.includes(:artist))
  end

  def create
    @playlist.songs.push(@songs)
    flash.now[:success] = t('success.add_to_playlist')

    # for refresh playlist content, when first song add to playlist
    show if @playlist.songs.size == 1
  rescue ActiveRecord::RecordNotUnique
    flash.now[:error] = t('error.already_in_playlist')
  end

  def destroy
    if songs_params[:clear_all]
      @playlist.songs.clear
    else
      @playlist.songs.destroy(@songs)
      flash.now[:success] = t('success.delete_from_playlist')
    end

    # for refresh playlist content, when remove last song from playlist
    show if @playlist.songs.empty?
  end

  private

    def find_playlist
      @playlist = Current.user.all_playlists.find(songs_params[:playlist_id])
    end

    def find_songs
      @songs = Song.find(songs_params[:song_ids]) unless songs_params[:clear_all]
    end

    def songs_params
      params.permit(:playlist_id, :clear_all, song_ids: [])
    end
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

class PlaylistsController < ApplicationController
  include Pagy::Backend

  before_action :require_login
  before_action :find_playlist, only: [:destroy, :update]

  def index
    @pagy, @playlists = pagy_countless(Current.user.playlists.order(created_at: :desc))
  end

  def create
    @playlist = Current.user.playlists.new playlist_params

    if @playlist.save
      flash.now[:success] = t('success.create')
    else
      flash.now[:error] = @playlist.errors.full_messages.join(' ')
    end
  end

  def update
    @playlist.update(playlist_params)
  end

  def destroy
    @playlist.destroy
    index; render 'index'
  end

  private

    def find_playlist
      @playlist = Current.user.playlists.find(params[:id])
    end

    def playlist_params
      params.require(:playlist).permit(:name)
    end
end

app/views/playlists/_index.html.erb
<%= form_with model: Playlist.new, class: 'form form--inline' do |form| %>
  <div class='input'>
    <%= form.text_field :name %>
  </div>
  <%= form.submit t('label.create'), class: 'button button--primary button--small' %>
<% end %>
<div data-controller='infinite-scroll' data-infinite-scroll-container='.playlist__container' data-infinite-scroll-next-url='<%= pagy_next_url(@pagy) %>'>
  <ul id='js-playlist-list' class='list'>
    <% if @playlists.present? %>
      <%= render partial: 'playlist', collection: @playlists, cached: true %>
    <% end %>
  </ul>
  <div data-target='infinite-scroll.trigger' class='display__justify-align-center'>
    <% if @pagy.next %>
      <%= loader_tag expand: true %>
    <% end %>
  </div>
</div>

app/views/playlists/_nav.html.erb
<ul class='tab'>
  <li class='tab__item <%= 'tab__item--active' if is_active?(path: current_playlist_songs_path) %>'>
    <%= link_to t('label.current'), current_playlist_songs_path, remote: true, data: { show_loader: true } %>
  </li>
  <li class='tab__item <%= 'tab__item--active' if is_active?(controller: ['playlists', 'playlists/songs']) %>'>
    <%= link_to t('label.playlists'), playlists_path, remote: true, data: { show_loader: true } %>
  </li>
  <li class='tab__item <%= 'tab__item--active' if is_active?(path: favorite_playlist_songs_path) %>'>
    <%= link_to t('label.favorites'), favorite_playlist_songs_path, remote: true, data: { show_loader: true } %>
  </li>
</ul>

app/views/playlists/_playlist.html.erb
<li>
  <%= link_to playlist_songs_path(playlist), remote: true, class: 'list__item', data: { show_loader: true } do %>
    <span class='list__item__content'>
      <span class='list__item__info list__item__info--main'>
        <%= playlist.name %>
      </span>
    </span>
    <span class='list__item__content list__item__content--minor'>
      <%= icon_tag('chevron-right') %>
    </span>
  <% end %>
</li>

app/views/playlists/create.js.erb
<%= render_flash %>

document.getElementById('playlist_name').value = '';

<% if @playlist.valid? %>
  document.querySelector('#js-playlist-list').insertAdjacentHTML('afterbegin', '<%= j(render partial: 'playlist', locals: { playlist: @playlist }) %>');
<% end %>

app/views/playlists/index.js.erb
<% if @pagy.page == 1 %>
  // If it's first page just render whole list content, avoid to add old playlist content to the new one.
  <%= render_playlist(render 'index') %>
<% else %>
  App.appedNextPageContentTo('#js-playlist-list', '<%= j(render partial: 'playlist', collection: @playlists, cached: true) %>', '<%= pagy_next_url(@pagy) %>')
<% end %>